name: Sync ok_school_life.py from Upstream

on:
  schedule:
    - cron: '*/10 * * * *'  # 每10分钟检查一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/still-alive-hhz/OK-School-Life.git || true
          git fetch upstream

      - name: Check file changes
        id: check-file
        run: |
          if ! git diff --quiet HEAD upstream/main -- ok_school_life.py; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "new_hash=$(git rev-parse upstream/main:ok_school_life.py)" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Sync changes
        if: steps.check-file.outputs.changed == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout upstream/main -- ok_school_life.py
          
          # 修复commit消息的变量引用
          COMMIT_MSG="AutoSync: Update ok_school_life.py from upstream (${{ steps.check-file.outputs.new_hash }})"
          git add ok_school_life.py
          git commit -m "$COMMIT_MSG"
          git push origin main